#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8
services:
#Linking Travis CI and Docker
- docker
before_install:
- docker build -t tylerdurdenhg/sample .
   
script:
- docker run tylerdurdenhg/sample -p 8080:80

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "sample"
  env: "Sample-env"
  bucket_name: "elasticbeanstalk-us-east-2-225288503576"
  bucket_path: "sample"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"